### ISSUE TITLE
use Auth in express router

### ISSUE THREAD

**Issue by tschnoelzer** [lucashuet93/botbuilder-simple-authentication#1]
Hi Lucas,

thx for your work ... I am trying to integrate in my Bot which is a set of adapters in different routes in express. So the router uses its own adapter. I have no server. when i pass a server instance from main app, then there is a conflict with this.server.use is not a function. When using the router in the this.server.address is not a function.

thx for a clue

Timo

**Comment by lucashuet93** [comment]
Hi Timo,

I apologize for the delay, I've just started the project and am wrapping up some core components, one of which will be to support express. I'll make sure and add support for router-only approaches as well. Thanks for reaching out, should be live in a few days and will update here.

**Comment by tschnoelzer** [comment]
Hi Lucas ... sounds good ! ... good luck for your work !!! ... will test when express routes are working ... best
Timo

Outlook für iOS<https://aka.ms/o0ukef> beziehen
________________________________

**Comment by lucashuet93** [comment]
Support for express applications and routers has been added. You'll want to update to 1.1, and the README has instructions on how to implement them, Let me know if you have any issues.

**Comment by tschnoelzer** [comment]
👍

Outlook für iOS<https://aka.ms/o0ukef> beziehen
________________________________
